-- Ecclesia initial migration (Sprint 1.3 - Database Foundation)
--
-- Rebuilt to match db/schema.prisma exactly, which was itself rebuilt
-- against the real Blueprint/PRD text in docs/. See db/DESIGN_NOTES.md for
-- the evidence behind every table/column below, tagged [BLUEPRINT-EXACT]
-- or [PRD-DERIVED], and for the open questions still outstanding. This
-- file was NOT generated by `prisma migrate dev` against a live database
-- (no PostgreSQL instance or package registry access was available in the
-- sandbox that authored it) - it must be validated for real before being
-- treated as trustworthy:
--
--   1. `prisma validate` (confirms this SQL and schema.prisma agree)
--   2. Apply to a real local PostgreSQL instance and confirm no errors
--   3. `prisma migrate diff` against the applied database, confirm empty
--
-- Implements, per db/migrations/README.md's commitment:
--   - the seven bounded-context Postgres schemas (Blueprint §7.2)
--   - Row-Level Security policies (Blueprint §7.3)
--   - the append-only Financial Transaction event model (Blueprint §7.4)
--   - the temporal GROUP_MEMBERSHIP model (Blueprint §7.5)

-- ===========================================================================
-- Extensions
-- ===========================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===========================================================================
-- Schemas - all seven bounded contexts (Blueprint §7.2)
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS people;
CREATE SCHEMA IF NOT EXISTS pastoral_care;
CREATE SCHEMA IF NOT EXISTS ministry;
CREATE SCHEMA IF NOT EXISTS gatherings;
CREATE SCHEMA IF NOT EXISTS stewardship;
CREATE SCHEMA IF NOT EXISTS insights;
CREATE SCHEMA IF NOT EXISTS platform;

-- ===========================================================================
-- Enums
-- ===========================================================================

CREATE TYPE people."Role" AS ENUM (
  'RESIDENT_PASTOR', 'ACTING_RESIDENT_PASTOR', 'ASSISTANT_PASTOR',
  'BACENTA_LEADER', 'BASONTA_LEADER', 'TREASURER', 'WORKER', 'MEMBER',
  'VISITOR', 'ADMIN', 'COUNCIL_OVERSEER'
);

-- [BLUEPRINT-EXACT] PRD §12.6 - PASTORAL_CARE (Bacenta) / MINISTRY
-- (Basonta) only, no Cluster type.
CREATE TYPE people."GroupType" AS ENUM ('PASTORAL_CARE', 'MINISTRY');

-- [BLUEPRINT-EXACT] PRD §12.6's Group lifecycle state diagram.
CREATE TYPE people."GroupLifecycleStatus" AS ENUM ('ACTIVE', 'SPLITTING', 'MERGING', 'ARCHIVED');

-- [BLUEPRINT-EXACT] PRD §12.5 / BR-PPL-03's exact 7-state list.
CREATE TYPE people."LifecycleStage" AS ENUM (
  'VISITOR', 'FIRST_TIME_GUEST', 'FOLLOW_UP', 'LAPSED',
  'ASSIGNED_TO_BACENTA', 'SIX_WEEKS_PARTICIPATION', 'MEMBER'
);

CREATE TYPE pastoral_care."PoimenStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE');
CREATE TYPE pastoral_care."SilentDriftStatus" AS ENUM ('FLAGGED', 'RESOLVED', 'ESCALATED');
CREATE TYPE pastoral_care."FollowUpTaskStatus" AS ENUM ('OPEN', 'ESCALATED', 'COMPLETED');

-- [BLUEPRINT-EXACT] Blueprint §7.4's `type` CHECK constraint, shown verbatim.
CREATE TYPE stewardship."FinancialTransactionType" AS ENUM (
  'OFFERING', 'TITHE', 'SPECIAL_OFFERING', 'PLEDGE', 'DONATION', 'EXPENSE'
);
CREATE TYPE stewardship."FinancialTransactionChannel" AS ENUM ('CASH', 'MOBILE_MONEY');
CREATE TYPE stewardship."ProjectStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');

CREATE TYPE gatherings."GatheringStatus" AS ENUM ('SCHEDULED', 'CANCELLED', 'COMPLETED');
-- [BLUEPRINT-EXACT] PRD §12.2: "a status (present, absent, excused)".
CREATE TYPE gatherings."AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'EXCUSED');

CREATE TYPE insights."AlertStatus" AS ENUM ('OPEN', 'ACTED', 'DISMISSED');
CREATE TYPE insights."PulseScoreScopeType" AS ENUM ('PERSON', 'GROUP', 'BRANCH');

CREATE TYPE platform."AuthMethod" AS ENUM ('PHONE_OTP', 'EMAIL_PASSWORD');
CREATE TYPE platform."AuthorizationEffect" AS ENUM ('ALLOW', 'DENY');

-- ===========================================================================
-- platform.councils / platform.branches
-- [PRD-DERIVED / BLUEPRINT-EXACT] FR-ADM-03; PRD §12.3's ERD:
-- COUNCIL ||--o{ BRANCH : oversees.
-- ===========================================================================

CREATE TABLE platform.councils (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE platform.branches (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  council_id UUID NOT NULL REFERENCES platform.councils (id) ON DELETE RESTRICT,
  name       TEXT NOT NULL,
  timezone   TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- people.groups - unifies Bacenta (PASTORAL_CARE) / Basonta (MINISTRY)
-- [BLUEPRINT-EXACT] PRD §12.6 - no Cluster type, no parent/child hierarchy.
-- ===========================================================================

CREATE TABLE people.groups (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id        UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  type             people."GroupType" NOT NULL,
  name             TEXT NOT NULL,
  -- [PRD-DERIVED] FR-PC-01 (Bacenta): name, leader, meeting schedule, location.
  meeting_schedule TEXT,
  meeting_location TEXT,
  -- [PRD-DERIVED] FR-MIN-01 (Basonta): name, leader, purpose/category.
  category         TEXT,
  lifecycle_status people."GroupLifecycleStatus" NOT NULL DEFAULT 'ACTIVE',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX groups_branch_id_type_idx ON people.groups (branch_id, type);

-- ===========================================================================
-- people.persons
-- [BLUEPRINT-EXACT] Blueprint §7.2: "includes optional nullable
-- guardian_person_id".
-- ===========================================================================

CREATE TABLE people.persons (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id          UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  first_name         TEXT NOT NULL,
  last_name          TEXT NOT NULL,
  phone              TEXT,
  email              TEXT,
  date_of_birth      DATE,
  address            TEXT,
  lifecycle_stage    people."LifecycleStage" NOT NULL DEFAULT 'VISITOR',
  guardian_person_id UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  -- [PRD-DERIVED] FR-PPL-08 - configurable custom profile fields.
  custom_fields      JSONB,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX persons_branch_id_idx ON people.persons (branch_id);
CREATE INDEX persons_guardian_person_id_idx ON people.persons (guardian_person_id);

-- ===========================================================================
-- platform.users / platform.sessions
-- [PRD-DERIVED] Blueprint §8 (Cognito-backed identity). Minimal shape -
-- see db/DESIGN_NOTES.md, full Cognito integration is Sprint 1.4's scope.
-- ===========================================================================

CREATE TABLE platform.users (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  person_id   UUID UNIQUE REFERENCES people.persons (id) ON DELETE SET NULL,
  cognito_sub TEXT NOT NULL UNIQUE,
  auth_method platform."AuthMethod" NOT NULL,
  phone       TEXT,
  email       TEXT,
  mfa_enabled BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX users_branch_id_idx ON platform.users (branch_id);

-- [PRD-DERIVED] Named in Blueprint §7.2's table list with no schema detail
-- elsewhere - see db/DESIGN_NOTES.md Open Question #4.
CREATE TABLE platform.sessions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES platform.users (id) ON DELETE CASCADE,
  device_id  TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ
);

CREATE INDEX sessions_user_id_idx ON platform.sessions (user_id);

-- ===========================================================================
-- people.role_assignments
-- ===========================================================================

CREATE TABLE people.role_assignments (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id         UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  role              people."Role" NOT NULL,
  branch_id         UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id          UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  -- [PRD-DERIVED] Open Question #1 - the Assistant Pastor "cluster" scope
  -- has no defined schema shape ("cluster assignment is itself a
  -- configuration" - PRD §17.2). Modeled as a plain array of Bacenta group
  -- ids; see db/DESIGN_NOTES.md.
  scope_group_ids   UUID[] NOT NULL DEFAULT '{}',
  granted_by_user_id UUID REFERENCES platform.users (id) ON DELETE SET NULL,
  effective_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  effective_to      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX role_assignments_person_id_effective_idx
  ON people.role_assignments (person_id, effective_from, effective_to);
CREATE INDEX role_assignments_branch_id_role_idx ON people.role_assignments (branch_id, role);

-- ===========================================================================
-- people.group_memberships - the temporal model
-- [BLUEPRINT-EXACT] Blueprint §7.5's exact DDL: started_at/ended_at,
-- required-on-close reason, partial unique index enforcing exactly one
-- active PASTORAL_CARE membership per person (BR-PPL-01).
-- ===========================================================================

CREATE TABLE people.group_memberships (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id  UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  group_id   UUID NOT NULL REFERENCES people.groups (id) ON DELETE CASCADE,
  group_type people."GroupType" NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at   TIMESTAMPTZ,
  reason     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX group_memberships_person_id_started_ended_idx
  ON people.group_memberships (person_id, started_at, ended_at);
CREATE INDEX group_memberships_group_id_started_ended_idx
  ON people.group_memberships (group_id, started_at, ended_at);
CREATE INDEX group_memberships_branch_id_idx ON people.group_memberships (branch_id);

-- [BLUEPRINT-EXACT] Blueprint §7.5's exact partial unique index.
CREATE UNIQUE INDEX one_active_bacenta_per_person ON people.group_memberships (person_id)
  WHERE group_type = 'PASTORAL_CARE' AND ended_at IS NULL;

-- ===========================================================================
-- platform.configurations
-- ===========================================================================

CREATE TABLE platform.configurations (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id             UUID NOT NULL UNIQUE REFERENCES platform.branches (id) ON DELETE CASCADE,
  gathering_types       TEXT[] NOT NULL,
  church_pulse_weights  JSONB NOT NULL,
  -- [BLUEPRINT-EXACT] Blueprint §9.3, exact field name.
  poimen_gate_enabled   BOOLEAN NOT NULL DEFAULT false,
  followup_sla_defaults JSONB NOT NULL,
  -- [PRD-DERIVED] PRD §15.8 - silent-drift N/M thresholds, Branch-configurable.
  silent_drift_config   JSONB NOT NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- platform.audit_log
-- ===========================================================================

CREATE TABLE platform.audit_log (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id     UUID REFERENCES platform.branches (id) ON DELETE SET NULL,
  actor_user_id UUID REFERENCES platform.users (id) ON DELETE SET NULL,
  action        TEXT NOT NULL,
  effect        platform."AuthorizationEffect",
  resource_type TEXT,
  resource_id   TEXT,
  reason        TEXT,
  device_id     TEXT,
  ip_address    TEXT,
  occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_log_branch_id_occurred_at_idx ON platform.audit_log (branch_id, occurred_at);

-- ===========================================================================
-- pastoral_care.poimen_enrollments
-- ===========================================================================

CREATE TABLE pastoral_care.poimen_enrollments (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id    UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  person_id    UUID NOT NULL UNIQUE REFERENCES people.persons (id) ON DELETE CASCADE,
  status       pastoral_care."PoimenStatus" NOT NULL DEFAULT 'NOT_STARTED',
  enrolled_at  TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- pastoral_care.follow_up_tasks
-- ===========================================================================

CREATE TABLE pastoral_care.follow_up_tasks (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id              UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id               UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  person_id              UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  assigned_to_person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  status                 pastoral_care."FollowUpTaskStatus" NOT NULL DEFAULT 'OPEN',
  due_at                 TIMESTAMPTZ,
  escalated_at           TIMESTAMPTZ,
  escalated_to_person_id UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  created_by_person_id   UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX follow_up_tasks_branch_id_status_idx ON pastoral_care.follow_up_tasks (branch_id, status);
CREATE INDEX follow_up_tasks_assigned_to_person_id_idx
  ON pastoral_care.follow_up_tasks (assigned_to_person_id);

-- ===========================================================================
-- pastoral_care.silent_drift_flags
-- [PRD-DERIVED] PRD §15.8's decision tree, operationalizing BR-PC-02.
-- ===========================================================================

CREATE TABLE pastoral_care.silent_drift_flags (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id                   UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id                    UUID NOT NULL REFERENCES people.groups (id) ON DELETE CASCADE,
  person_id                   UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  attendance_missed_count     INTEGER NOT NULL,
  attendance_threshold        INTEGER NOT NULL,
  bacenta_missed_count        INTEGER NOT NULL,
  bacenta_threshold           INTEGER NOT NULL,
  status                      pastoral_care."SilentDriftStatus" NOT NULL DEFAULT 'FLAGGED',
  assigned_shepherd_person_id UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  resolved_at                 TIMESTAMPTZ,
  escalated_at                TIMESTAMPTZ,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX silent_drift_flags_branch_id_status_idx ON pastoral_care.silent_drift_flags (branch_id, status);

-- ===========================================================================
-- pastoral_care.pastoral_notes - no update action exists in libs/rbac;
-- likely immutable once created (unconfirmed, no mutation-blocking trigger
-- added here without that confirmation)
-- ===========================================================================

CREATE TABLE pastoral_care.pastoral_notes (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id        UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  person_id        UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  author_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  content          TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX pastoral_notes_branch_id_idx ON pastoral_care.pastoral_notes (branch_id);
CREATE INDEX pastoral_notes_person_id_idx ON pastoral_care.pastoral_notes (person_id);

-- ===========================================================================
-- gatherings.gathering_series / gatherings.gatherings
-- [BLUEPRINT-EXACT] PRD §12.4's exact field list for Gathering.
-- ===========================================================================

CREATE TABLE gatherings.gathering_series (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id             UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  type                 TEXT NOT NULL,
  recurrence_rule      TEXT,
  start_date           DATE NOT NULL,
  end_date             DATE,
  created_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX gathering_series_branch_id_idx ON gatherings.gathering_series (branch_id);

CREATE TABLE gatherings.gatherings (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  owner_group_id       UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  series_id            UUID REFERENCES gatherings.gathering_series (id) ON DELETE SET NULL,
  type                 TEXT NOT NULL,
  scheduled_start      TIMESTAMPTZ NOT NULL,
  scheduled_end        TIMESTAMPTZ,
  venue                TEXT,
  status               gatherings."GatheringStatus" NOT NULL DEFAULT 'SCHEDULED',
  config               JSONB,
  created_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX gatherings_branch_id_scheduled_start_idx ON gatherings.gatherings (branch_id, scheduled_start);
CREATE INDEX gatherings_owner_group_id_scheduled_start_idx ON gatherings.gatherings (owner_group_id, scheduled_start);

-- ===========================================================================
-- ministry.staffing_targets / ministry.worker_availability
-- [PRD-DERIVED] FR-MIN-02; §16.3.
-- ===========================================================================

CREATE TABLE ministry.staffing_targets (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  gathering_id         UUID NOT NULL REFERENCES gatherings.gatherings (id) ON DELETE CASCADE,
  group_id             UUID NOT NULL REFERENCES people.groups (id) ON DELETE CASCADE,
  target_count         INTEGER NOT NULL,
  created_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (gathering_id, group_id)
);

CREATE INDEX staffing_targets_branch_id_idx ON ministry.staffing_targets (branch_id);

CREATE TABLE ministry.worker_availability (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id        UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  person_id        UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  unavailable_from DATE NOT NULL,
  unavailable_to   DATE NOT NULL,
  reason           TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX worker_availability_person_id_range_idx
  ON ministry.worker_availability (person_id, unavailable_from, unavailable_to);
CREATE INDEX worker_availability_branch_id_idx ON ministry.worker_availability (branch_id);

-- ===========================================================================
-- gatherings.attendance_records
-- [BLUEPRINT-EXACT] Renamed from `attendance` to match the Blueprint.
-- PRD §12.2's exact 3-value status. branch_id denormalized so the RLS
-- policy stays a plain column comparison, not a join.
-- ===========================================================================

CREATE TABLE gatherings.attendance_records (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gathering_id          UUID NOT NULL REFERENCES gatherings.gatherings (id) ON DELETE CASCADE,
  person_id             UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  branch_id             UUID NOT NULL,
  status                gatherings."AttendanceStatus" NOT NULL,
  recorded_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  recorded_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (gathering_id, person_id)
);

CREATE INDEX attendance_records_branch_id_idx ON gatherings.attendance_records (branch_id);

-- ===========================================================================
-- gatherings.visitor_intake_submissions
-- [PRD-DERIVED] FR-GTH-04; §16.1's minimal capture fields.
-- ===========================================================================

CREATE TABLE gatherings.visitor_intake_submissions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id      UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  gathering_id   UUID REFERENCES gatherings.gatherings (id) ON DELETE SET NULL,
  person_id      UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  submitted_data JSONB NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX visitor_intake_submissions_branch_id_idx ON gatherings.visitor_intake_submissions (branch_id);

-- ===========================================================================
-- stewardship.financial_transactions / financial_transaction_events
-- [BLUEPRINT-EXACT] Blueprint §7.4's full DDL, shown verbatim: header row
-- plus append-only event log, amount stored as amount_minor BIGINT.
-- ===========================================================================

CREATE TABLE stewardship.financial_transactions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id       UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  type            stewardship."FinancialTransactionType" NOT NULL,
  source_group_id UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  giver_person_id UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  channel         stewardship."FinancialTransactionChannel",
  amount_minor    BIGINT NOT NULL,
  currency        CHAR(3) NOT NULL DEFAULT 'GHS',
  current_state   TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX financial_transactions_branch_id_type_state_idx
  ON stewardship.financial_transactions (branch_id, type, current_state);

CREATE TABLE stewardship.financial_transaction_events (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id UUID NOT NULL REFERENCES stewardship.financial_transactions (id) ON DELETE CASCADE,
  from_state     TEXT,
  to_state       TEXT NOT NULL,
  actor_user_id  UUID NOT NULL REFERENCES platform.users (id) ON DELETE RESTRICT,
  reason         TEXT,
  occurred_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX financial_transaction_events_transaction_id_idx
  ON stewardship.financial_transaction_events (transaction_id);

-- Append-only enforcement. Blueprint §7.4's actual mechanism is a REVOKE
-- on UPDATE/DELETE grants for the application's database role, not a
-- trigger - that requires a dedicated non-owner application role, which
-- doesn't exist yet (see db/DESIGN_NOTES.md Open Question #2). This
-- trigger is an interim safeguard so the append-only guarantee holds even
-- before that role exists; it should be reconsidered (possibly removed in
-- favor of pure REVOKE) once the role is set up.
CREATE FUNCTION stewardship.prevent_financial_transaction_event_mutation()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    'financial_transaction_events is append-only (Blueprint §7.4) - % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER financial_transaction_events_no_update
  BEFORE UPDATE ON stewardship.financial_transaction_events
  FOR EACH ROW EXECUTE FUNCTION stewardship.prevent_financial_transaction_event_mutation();

CREATE TRIGGER financial_transaction_events_no_delete
  BEFORE DELETE ON stewardship.financial_transaction_events
  FOR EACH ROW EXECUTE FUNCTION stewardship.prevent_financial_transaction_event_mutation();

-- ===========================================================================
-- stewardship.expenses
-- [PRD-DERIVED] FR-STW-09. Modeled as a 1:1 extension of a
-- financial_transactions row with type=EXPENSE - see
-- db/DESIGN_NOTES.md Open Question #5.
-- ===========================================================================

CREATE TABLE stewardship.expenses (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id              UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  transaction_id         UUID NOT NULL UNIQUE REFERENCES stewardship.financial_transactions (id) ON DELETE CASCADE,
  requested_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  description            TEXT NOT NULL,
  category               TEXT,
  receipt_storage_key    TEXT,
  approved_by_person_id  UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  approved_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX expenses_branch_id_idx ON stewardship.expenses (branch_id);

-- ===========================================================================
-- stewardship.projects / stewardship.pledges
-- [PRD-DERIVED] FR-STW-08 / H2.
-- ===========================================================================

CREATE TABLE stewardship.projects (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  name                 TEXT NOT NULL,
  description          TEXT,
  target_amount_minor  BIGINT NOT NULL,
  currency             CHAR(3) NOT NULL DEFAULT 'GHS',
  status               stewardship."ProjectStatus" NOT NULL DEFAULT 'ACTIVE',
  created_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX projects_branch_id_status_idx ON stewardship.projects (branch_id, status);

CREATE TABLE stewardship.pledges (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id                UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  project_id               UUID NOT NULL REFERENCES stewardship.projects (id) ON DELETE CASCADE,
  person_id                UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  pledged_amount_minor     BIGINT NOT NULL,
  currency                 CHAR(3) NOT NULL DEFAULT 'GHS',
  pledged_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  reminder_opt_in          BOOLEAN NOT NULL DEFAULT false,
  reminder_sent_at         TIMESTAMPTZ,
  fulfilled_transaction_id UUID REFERENCES stewardship.financial_transactions (id) ON DELETE SET NULL,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX pledges_project_id_idx ON stewardship.pledges (project_id);
CREATE INDEX pledges_person_id_idx ON stewardship.pledges (person_id);
CREATE INDEX pledges_branch_id_idx ON stewardship.pledges (branch_id);

-- ===========================================================================
-- insights.engagement_signals / pulse_scores / pulse_score_history / alerts
-- [PRD-DERIVED] PRD §12.8's flowchart; FR-INS-01/03/05.
-- ===========================================================================

CREATE TABLE insights.engagement_signals (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  -- person_id intentionally has no FK constraint - see
  -- db/schema.prisma's comment on EngagementSignal.personId.
  person_id   UUID,
  group_id    UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  signal_type TEXT NOT NULL,
  payload     JSONB NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX engagement_signals_branch_id_type_occurred_idx
  ON insights.engagement_signals (branch_id, signal_type, occurred_at);
CREATE INDEX engagement_signals_person_id_idx ON insights.engagement_signals (person_id);

-- Current/latest score per scope; pulse_score_history holds the full time
-- series - see db/DESIGN_NOTES.md Open Question #7.
CREATE TABLE insights.pulse_scores (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  scope_type  insights."PulseScoreScopeType" NOT NULL,
  scope_id    UUID NOT NULL,
  score       DECIMAL(5, 2) NOT NULL,
  computed_at TIMESTAMPTZ NOT NULL,
  UNIQUE (scope_type, scope_id)
);

CREATE INDEX pulse_scores_branch_id_scope_type_idx ON insights.pulse_scores (branch_id, scope_type);

CREATE TABLE insights.pulse_score_history (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  scope_type  insights."PulseScoreScopeType" NOT NULL,
  scope_id    UUID NOT NULL,
  score       DECIMAL(5, 2) NOT NULL,
  computed_at TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX pulse_score_history_branch_scope_computed_idx
  ON insights.pulse_score_history (branch_id, scope_type, scope_id, computed_at);

CREATE TABLE insights.alerts (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  scope_type           insights."PulseScoreScopeType" NOT NULL,
  scope_id             UUID NOT NULL,
  alert_type           TEXT NOT NULL,
  message              TEXT,
  status               insights."AlertStatus" NOT NULL DEFAULT 'OPEN',
  resolved_by_person_id UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  resolved_at          TIMESTAMPTZ,
  triggered_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX alerts_branch_id_status_idx ON insights.alerts (branch_id, status);

-- ===========================================================================
-- Row-Level Security (Blueprint §7.3)
--
-- Every Branch-scoped table gets RLS enabled with a policy comparing its
-- branch_id column to the current session's app.current_branch_id setting.
-- [BLUEPRINT-EXACT] Blueprint §7.3's exact policy expression:
--   USING (branch_id = current_setting('app.current_branch_id')::uuid)
-- with NO second `true` (missing_ok) argument to current_setting - the
-- first draft of this migration used `current_setting(..., true)`, which
-- silently returns NULL instead of raising when the session variable is
-- unset. The Blueprint's version hard-fails in that case, which is the
-- correct fail-closed behavior for a security backstop and has been
-- corrected here to match exactly.
--
-- This is a BACKSTOP under application-layer filtering (RBAC in
-- libs/rbac), not a replacement for it.
--
-- IMPORTANT, and not yet wired anywhere (see db/DESIGN_NOTES.md Open
-- Question #3): nothing in this migration sets app.current_branch_id, and
-- Postgres bypasses RLS entirely for the table owner unless FORCE ROW
-- LEVEL SECURITY is also set (deliberately not set here, since migrations
-- and seeding need to write cross-Branch data as the owning role). For RLS
-- to do anything at runtime, the application must connect as a different,
-- non-owner Postgres role, and a Prisma middleware/interceptor must run
-- `SET LOCAL app.current_branch_id = '<uuid>'` at the start of every
-- request-scoped transaction. Neither exists yet.
-- ===========================================================================

ALTER TABLE people.groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY groups_branch_isolation ON people.groups
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE people.persons ENABLE ROW LEVEL SECURITY;
CREATE POLICY persons_branch_isolation ON people.persons
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE people.role_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY role_assignments_branch_isolation ON people.role_assignments
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE people.group_memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_memberships_branch_isolation ON people.group_memberships
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE platform.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_branch_isolation ON platform.users
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE platform.configurations ENABLE ROW LEVEL SECURITY;
CREATE POLICY configurations_branch_isolation ON platform.configurations
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE platform.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_log_branch_isolation ON platform.audit_log
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE pastoral_care.poimen_enrollments ENABLE ROW LEVEL SECURITY;
CREATE POLICY poimen_enrollments_branch_isolation ON pastoral_care.poimen_enrollments
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE pastoral_care.follow_up_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY follow_up_tasks_branch_isolation ON pastoral_care.follow_up_tasks
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE pastoral_care.silent_drift_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY silent_drift_flags_branch_isolation ON pastoral_care.silent_drift_flags
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

-- Pastoral notes are the most sensitive data in this schema (PRD §17.3;
-- ADMIN is explicitly DENYed read access in libs/rbac's permission matrix
-- per NFR-PRIV-01). RLS here is a deliberate extra backstop even though it
-- is the same branch_id policy shape as every other table.
ALTER TABLE pastoral_care.pastoral_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY pastoral_notes_branch_isolation ON pastoral_care.pastoral_notes
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE ministry.staffing_targets ENABLE ROW LEVEL SECURITY;
CREATE POLICY staffing_targets_branch_isolation ON ministry.staffing_targets
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE ministry.worker_availability ENABLE ROW LEVEL SECURITY;
CREATE POLICY worker_availability_branch_isolation ON ministry.worker_availability
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE gatherings.gathering_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY gathering_series_branch_isolation ON gatherings.gathering_series
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE gatherings.gatherings ENABLE ROW LEVEL SECURITY;
CREATE POLICY gatherings_branch_isolation ON gatherings.gatherings
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE gatherings.attendance_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY attendance_records_branch_isolation ON gatherings.attendance_records
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE gatherings.visitor_intake_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY visitor_intake_submissions_branch_isolation ON gatherings.visitor_intake_submissions
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE stewardship.financial_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY financial_transactions_branch_isolation ON stewardship.financial_transactions
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

-- financial_transaction_events has no direct branch_id column (Blueprint
-- §7.4's DDL doesn't include one on the event log) - scoped via a
-- subquery against its parent transaction instead.
ALTER TABLE stewardship.financial_transaction_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY financial_transaction_events_branch_isolation ON stewardship.financial_transaction_events
  USING (
    transaction_id IN (
      SELECT id FROM stewardship.financial_transactions
      WHERE branch_id = current_setting('app.current_branch_id')::uuid
    )
  );

ALTER TABLE stewardship.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY expenses_branch_isolation ON stewardship.expenses
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE stewardship.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY projects_branch_isolation ON stewardship.projects
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE stewardship.pledges ENABLE ROW LEVEL SECURITY;
CREATE POLICY pledges_branch_isolation ON stewardship.pledges
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE insights.engagement_signals ENABLE ROW LEVEL SECURITY;
CREATE POLICY engagement_signals_branch_isolation ON insights.engagement_signals
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE insights.pulse_scores ENABLE ROW LEVEL SECURITY;
CREATE POLICY pulse_scores_branch_isolation ON insights.pulse_scores
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE insights.pulse_score_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY pulse_score_history_branch_isolation ON insights.pulse_score_history
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

ALTER TABLE insights.alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY alerts_branch_isolation ON insights.alerts
  USING (branch_id = current_setting('app.current_branch_id')::uuid);

-- platform.branches itself: a row's own id, not a branch_id column, is
-- what's compared.
ALTER TABLE platform.branches ENABLE ROW LEVEL SECURITY;
CREATE POLICY branches_self_isolation ON platform.branches
  USING (id = current_setting('app.current_branch_id')::uuid);
