-- Ecclesia initial migration (Sprint 1.3 - Database Foundation)
--
-- DRAFT, hand-written to match db/schema.prisma exactly - see
-- db/DESIGN_NOTES.md for the evidence behind every decision below and the
-- open questions still outstanding. This file was NOT generated by
-- `prisma migrate dev` against a live database (no PostgreSQL instance or
-- package registry access was available in the environment that authored
-- it) - it must be validated for real before being treated as trustworthy:
--
--   1. `prisma validate` (confirms this SQL and schema.prisma agree)
--   2. Apply to a real local PostgreSQL instance and confirm no errors
--   3. `prisma migrate diff` against the applied database, confirm empty
--
-- Implements, per db/migrations/README.md's commitment:
--   - the seven bounded-context Postgres schemas (Blueprint §7.2)
--   - Row-Level Security policies (Blueprint §7.3)
--   - the append-only Financial Transaction event log (Blueprint §7.4)
--   - the temporal GROUP_MEMBERSHIP model (Blueprint §7.5)

-- ===========================================================================
-- Extensions
-- ===========================================================================

-- gen_random_uuid() is built into PostgreSQL 13+ without an extension, but
-- pgcrypto is enabled explicitly so this migration also works on older
-- supported versions without a separate code path.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===========================================================================
-- Schemas - all seven bounded contexts (Blueprint §7.2)
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS people;
CREATE SCHEMA IF NOT EXISTS pastoral_care;
-- ministry and insights have no tables yet - see db/DESIGN_NOTES.md's
-- "Deliberately not built" section. The schemas themselves are created
-- here because the bounded-context boundary is what Blueprint §7.2 counts
-- as "seven schemas," independent of whether each has tables yet.
CREATE SCHEMA IF NOT EXISTS ministry;
CREATE SCHEMA IF NOT EXISTS gatherings;
CREATE SCHEMA IF NOT EXISTS stewardship;
CREATE SCHEMA IF NOT EXISTS insights;
CREATE SCHEMA IF NOT EXISTS platform;

-- ===========================================================================
-- Enums
-- ===========================================================================

-- Mirrors libs/rbac/src/lib/roles.ts's ROLES array exactly.
CREATE TYPE people."Role" AS ENUM (
  'RESIDENT_PASTOR',
  'ACTING_RESIDENT_PASTOR',
  'ASSISTANT_PASTOR',
  'BACENTA_LEADER',
  'BASONTA_LEADER',
  'TREASURER',
  'WORKER',
  'MEMBER',
  'VISITOR',
  'ADMIN',
  'COUNCIL_OVERSEER'
);

CREATE TYPE people."PoimenStatus" AS ENUM (
  'NOT_STARTED',
  'IN_PROGRESS',
  'COMPLETE'
);

CREATE TYPE people."GroupType" AS ENUM (
  'CLUSTER',
  'BACENTA',
  'BASONTA'
);

CREATE TYPE stewardship."FinancialTransactionEventType" AS ENUM (
  'RECORDED',
  'VERIFIED',
  'RECONCILED'
);

CREATE TYPE stewardship."ExpenseStatus" AS ENUM (
  'REQUESTED',
  'APPROVED'
);

CREATE TYPE platform."AuthorizationEffect" AS ENUM (
  'ALLOW',
  'DENY'
);

-- ===========================================================================
-- platform.branches - the org root every ActorContext.branchId refers to
-- ===========================================================================

CREATE TABLE platform.branches (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  timezone   TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- people.groups - unifies Cluster/Bacenta/Basonta (see DESIGN_NOTES §1)
-- ===========================================================================

CREATE TABLE people.groups (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id       UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  type            people."GroupType" NOT NULL,
  parent_group_id UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  name            TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX groups_branch_id_type_idx ON people.groups (branch_id, type);

-- ===========================================================================
-- people.persons
-- ===========================================================================

CREATE TABLE people.persons (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id       UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  first_name      TEXT NOT NULL,
  last_name       TEXT NOT NULL,
  phone           TEXT,
  email           TEXT,
  -- PRD §12.5's lifecycle-stage state machine - state names not evidenced
  -- anywhere in this repo, so left unconstrained (see DESIGN_NOTES §2).
  lifecycle_stage TEXT NOT NULL,
  poimen_status   people."PoimenStatus" NOT NULL DEFAULT 'NOT_STARTED',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX persons_branch_id_idx ON people.persons (branch_id);

-- ===========================================================================
-- people.role_assignments - time-bound (libs/rbac/src/lib/roles.ts)
-- ===========================================================================

CREATE TABLE people.role_assignments (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id             UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  role                  people."Role" NOT NULL,
  branch_id             UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id              UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  granted_by_person_id  UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  effective_from        TIMESTAMPTZ NOT NULL DEFAULT now(),
  effective_to          TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX role_assignments_person_id_effective_idx
  ON people.role_assignments (person_id, effective_from, effective_to);
CREATE INDEX role_assignments_branch_id_role_idx ON people.role_assignments (branch_id, role);

-- ===========================================================================
-- people.group_memberships - the temporal model, Blueprint §7.5
-- ===========================================================================

CREATE TABLE people.group_memberships (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  -- Must reference a Group with type BACENTA or BASONTA - enforced at the
  -- application layer for now, not a DB constraint (DESIGN_NOTES §3).
  group_id   UUID NOT NULL REFERENCES people.groups (id) ON DELETE CASCADE,
  valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to   TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX group_memberships_person_id_valid_idx
  ON people.group_memberships (person_id, valid_from, valid_to);
CREATE INDEX group_memberships_group_id_valid_idx
  ON people.group_memberships (group_id, valid_from, valid_to);

-- ===========================================================================
-- platform.configurations - table name taken verbatim from
-- libs/rbac/src/lib/types.ts's BranchConfiguration doc comment
-- ===========================================================================

CREATE TABLE platform.configurations (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id              UUID NOT NULL UNIQUE REFERENCES platform.branches (id) ON DELETE CASCADE,
  gathering_types        TEXT[] NOT NULL,
  church_pulse_weights   JSONB NOT NULL,
  poimen_gate_enabled    BOOLEAN NOT NULL DEFAULT false,
  followup_sla_defaults  JSONB NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- platform.audit_log - backs the scoped platform.audit_log.read action
-- ===========================================================================

CREATE TABLE platform.audit_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id       UUID REFERENCES platform.branches (id) ON DELETE SET NULL,
  actor_person_id UUID NOT NULL,
  action          TEXT NOT NULL,
  effect          platform."AuthorizationEffect" NOT NULL,
  resource_type   TEXT,
  resource_id     TEXT,
  reason          TEXT NOT NULL,
  occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_log_branch_id_occurred_at_idx ON platform.audit_log (branch_id, occurred_at);

-- ===========================================================================
-- gatherings.gathering_series - supports recurrence-series handling
-- ===========================================================================

CREATE TABLE gatherings.gathering_series (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id             UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id              UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  gathering_type        TEXT NOT NULL,
  recurrence_rule       TEXT,
  start_date            TIMESTAMPTZ NOT NULL,
  end_date              TIMESTAMPTZ,
  created_by_person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX gathering_series_branch_id_idx ON gatherings.gathering_series (branch_id);

-- ===========================================================================
-- gatherings.gatherings - "Everything Is A Gathering"
-- ===========================================================================

CREATE TABLE gatherings.gatherings (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id             UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id              UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  series_id             UUID REFERENCES gatherings.gathering_series (id) ON DELETE SET NULL,
  gathering_type        TEXT NOT NULL,
  scheduled_at          TIMESTAMPTZ NOT NULL,
  created_by_person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX gatherings_branch_id_scheduled_at_idx ON gatherings.gatherings (branch_id, scheduled_at);
CREATE INDEX gatherings_group_id_scheduled_at_idx ON gatherings.gatherings (group_id, scheduled_at);

-- ===========================================================================
-- gatherings.attendance - a row's existence means "present" (no status enum)
-- ===========================================================================

CREATE TABLE gatherings.attendance (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gathering_id           UUID NOT NULL REFERENCES gatherings.gatherings (id) ON DELETE CASCADE,
  person_id              UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  -- Denormalized from gatherings.gatherings deliberately, so the RLS
  -- policy on this table is a plain column comparison, not a subquery.
  branch_id              UUID NOT NULL,
  recorded_by_person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  recorded_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (gathering_id, person_id)
);

CREATE INDEX attendance_branch_id_idx ON gatherings.attendance (branch_id);

-- ===========================================================================
-- stewardship.financial_transaction_events - append-only event log,
-- Blueprint §7.4
-- ===========================================================================

CREATE TABLE stewardship.financial_transaction_events (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id         UUID NOT NULL,
  event_type             stewardship."FinancialTransactionEventType" NOT NULL,
  amount                 DECIMAL(12, 2) NOT NULL,
  currency               CHAR(3) NOT NULL,
  branch_id              UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  group_id               UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  actor_person_id        UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  -- Set on VERIFIED/RECONCILED events - copied from the transaction's
  -- original RECORDED event so BR-STW-04 (DIFFERENT_ACTOR_THAN_RECORDER)
  -- can be checked without joining back to it.
  recorded_by_person_id  UUID REFERENCES people.persons (id) ON DELETE RESTRICT,
  occurred_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata               JSONB,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX financial_transaction_events_transaction_id_idx
  ON stewardship.financial_transaction_events (transaction_id);
CREATE INDEX financial_transaction_events_branch_id_occurred_at_idx
  ON stewardship.financial_transaction_events (branch_id, occurred_at);

-- Append-only enforcement: nothing may UPDATE or DELETE a row in this
-- table, ever - "append-only event log" (db/migrations/README.md) is
-- enforced here, not left as a convention the application layer might
-- forget. Migrations/seed scripts that legitimately need to fix data
-- (extremely rare, and only ever pre-launch) must do so by dropping and
-- recreating this trigger explicitly, not by finding a quiet way around it.
CREATE FUNCTION stewardship.prevent_financial_transaction_event_mutation()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    'financial_transaction_events is append-only (Blueprint §7.4) - % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER financial_transaction_events_no_update
  BEFORE UPDATE ON stewardship.financial_transaction_events
  FOR EACH ROW EXECUTE FUNCTION stewardship.prevent_financial_transaction_event_mutation();

CREATE TRIGGER financial_transaction_events_no_delete
  BEFORE DELETE ON stewardship.financial_transaction_events
  FOR EACH ROW EXECUTE FUNCTION stewardship.prevent_financial_transaction_event_mutation();

-- ===========================================================================
-- stewardship.expenses
-- ===========================================================================

CREATE TABLE stewardship.expenses (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id              UUID NOT NULL REFERENCES platform.branches (id) ON DELETE RESTRICT,
  requested_by_person_id UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  amount                 DECIMAL(12, 2) NOT NULL,
  currency               CHAR(3) NOT NULL,
  status                 stewardship."ExpenseStatus" NOT NULL DEFAULT 'REQUESTED',
  approved_by_person_id  UUID REFERENCES people.persons (id) ON DELETE SET NULL,
  approved_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX expenses_branch_id_status_idx ON stewardship.expenses (branch_id, status);

-- ===========================================================================
-- pastoral_care.followup_tasks
-- ===========================================================================

CREATE TABLE pastoral_care.followup_tasks (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id               UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  group_id                UUID REFERENCES people.groups (id) ON DELETE SET NULL,
  person_id               UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  assigned_to_person_id   UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  -- Not evidenced beyond create/update/read actions existing (DESIGN_NOTES §9).
  status                  TEXT NOT NULL,
  due_at                  TIMESTAMPTZ,
  created_by_person_id    UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX followup_tasks_branch_id_status_idx ON pastoral_care.followup_tasks (branch_id, status);
CREATE INDEX followup_tasks_assigned_to_person_id_idx
  ON pastoral_care.followup_tasks (assigned_to_person_id);

-- ===========================================================================
-- pastoral_care.pastoral_notes - no update action exists in libs/rbac;
-- possibly immutable like the financial event log (unconfirmed, no
-- mutation-blocking trigger added here without that confirmation)
-- ===========================================================================

CREATE TABLE pastoral_care.pastoral_notes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id         UUID NOT NULL REFERENCES platform.branches (id) ON DELETE CASCADE,
  person_id         UUID NOT NULL REFERENCES people.persons (id) ON DELETE CASCADE,
  author_person_id  UUID NOT NULL REFERENCES people.persons (id) ON DELETE RESTRICT,
  content           TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX pastoral_notes_branch_id_idx ON pastoral_care.pastoral_notes (branch_id);
CREATE INDEX pastoral_notes_person_id_idx ON pastoral_care.pastoral_notes (person_id);

-- ===========================================================================
-- Row-Level Security (Blueprint §7.3)
--
-- Every Branch-scoped table gets RLS enabled with a policy comparing its
-- branch_id column to the current session's app.current_branch_id setting.
-- This is a BACKSTOP under application-layer filtering (RBAC in
-- libs/rbac), not a replacement for it - engineering-principles.md §5
-- states this explicitly, and DESIGN_NOTES §6 flags that the mechanism
-- below (session GUC name, exact policy shape) is not evidenced by the
-- Blueprint text and needs confirmation.
--
-- IMPORTANT, and not yet wired anywhere: nothing in this migration sets
-- app.current_branch_id. Postgres also bypasses RLS entirely for the
-- table owner (the role that runs migrations) unless FORCE ROW LEVEL
-- SECURITY is also set - deliberately NOT set here, because the
-- migration/seed process needs to write cross-Branch data as the owning
-- role. For RLS to do anything at runtime, the application must connect
-- as a *different*, non-owner Postgres role, and something (a Prisma
-- middleware/interceptor populating from EcclesiaRequestContext, per
-- libs/rbac) must run `SET LOCAL app.current_branch_id = '<uuid>'` at the
-- start of every request-scoped transaction. Both the runtime role and
-- that middleware are unbuilt - see db/DESIGN_NOTES.md's closing section.
-- ===========================================================================

ALTER TABLE people.groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY groups_branch_isolation ON people.groups
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE people.persons ENABLE ROW LEVEL SECURITY;
CREATE POLICY persons_branch_isolation ON people.persons
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE people.role_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY role_assignments_branch_isolation ON people.role_assignments
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

-- group_memberships has no direct branch_id column - scoped via a
-- subquery against people.groups instead. Slower than a plain column
-- comparison (see the deliberate branch_id denormalization on
-- gatherings.attendance, done for exactly this reason), acceptable here
-- pending the open question in DESIGN_NOTES §6 about whether RLS should
-- extend below Branch-level at all.
ALTER TABLE people.group_memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_memberships_branch_isolation ON people.group_memberships
  USING (
    group_id IN (
      SELECT id FROM people.groups
      WHERE branch_id = current_setting('app.current_branch_id', true)::uuid
    )
  );

ALTER TABLE platform.configurations ENABLE ROW LEVEL SECURITY;
CREATE POLICY configurations_branch_isolation ON platform.configurations
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE platform.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_log_branch_isolation ON platform.audit_log
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE gatherings.gathering_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY gathering_series_branch_isolation ON gatherings.gathering_series
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE gatherings.gatherings ENABLE ROW LEVEL SECURITY;
CREATE POLICY gatherings_branch_isolation ON gatherings.gatherings
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE gatherings.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY attendance_branch_isolation ON gatherings.attendance
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE stewardship.financial_transaction_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY financial_transaction_events_branch_isolation ON stewardship.financial_transaction_events
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE stewardship.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY expenses_branch_isolation ON stewardship.expenses
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

ALTER TABLE pastoral_care.followup_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY followup_tasks_branch_isolation ON pastoral_care.followup_tasks
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

-- Pastoral notes are the most sensitive data in this schema (PRD §17.3
-- marks them sensitive; ADMIN is explicitly DENYed read access in
-- libs/rbac's permission matrix despite ADMIN's broad configuration
-- authority, per NFR-PRIV-01). RLS here is a deliberate extra backstop
-- even though it is the same branch_id policy shape as every other table.
ALTER TABLE pastoral_care.pastoral_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY pastoral_notes_branch_isolation ON pastoral_care.pastoral_notes
  USING (branch_id = current_setting('app.current_branch_id', true)::uuid);

-- platform.branches itself: a row's own id, not a branch_id column, is
-- what's compared.
ALTER TABLE platform.branches ENABLE ROW LEVEL SECURITY;
CREATE POLICY branches_self_isolation ON platform.branches
  USING (id = current_setting('app.current_branch_id', true)::uuid);
